# Generated by Django 2.1.7 on 2019-02-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config_instagram_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('START_SLEEP_TIME_LIKE', models.CharField(default='20', max_length=4)),
                ('FINISH_SLEEP_TIME_LIKE', models.CharField(default='35', max_length=4)),
                ('START_SLEEP_TIME_FOLLOWER', models.CharField(default='5', max_length=4)),
                ('FINISH_SLEEP_TIME_FOLLOWER', models.CharField(default='12', max_length=4)),
                ('START_COUNT_POSTS', models.CharField(default='4', max_length=4)),
                ('FINISH_COUNT_POSTS', models.CharField(default='9', max_length=4)),
                ('MAX_LIKE_PER_DAY', models.CharField(default='1000', max_length=4)),
                ('TIME_LAST_ACTIVITY_LIKE', models.CharField(default='1814400', max_length=10)),
                ('START_SLEEP_TIME_TO_FOLLOW', models.CharField(default='30', max_length=10)),
                ('FINISH_SLEEP_TIME_TO_FOLLOW', models.CharField(default='40', max_length=10)),
                ('START_SLEEP_TIME_TO_UNFOLLOW', models.CharField(default='15', max_length=10)),
                ('FINISH_SLEEP_TIME_TO_UNFOLLOW', models.CharField(default='25', max_length=10)),
                ('MAX_FOLLOWING_USERS_PER_HOUR', models.CharField(default='200', max_length=4)),
                ('MAX_FOLLOWING_USERS_PER_DAY', models.CharField(default='1000', max_length=4)),
                ('MAX_RELATIVE_UNFOLLOWING_USERS_PER_DAY', models.CharField(default='1000', max_length=10)),
                ('MAX_UNRELATED_UNFOLLOWING_USERS_PER_DAY', models.CharField(default='1000', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Conn_acc_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=32)),
                ('avatar_link', models.CharField(default='', max_length=256)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conn_inst_acc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(db_index=True, max_length=32, unique=True)),
                ('passwd', models.CharField(max_length=32)),
                ('mass_likes', models.BooleanField(default='False')),
                ('mass_follow', models.BooleanField(default='False')),
                ('mass_resort', models.BooleanField(default='False')),
                ('first_load', models.BooleanField(default='True')),
                ('config', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Config_instagram_work')),
            ],
        ),
        migrations.CreateModel(
            name='Conn_inst_followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_follow', models.CharField(max_length=10)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('like_last_date', models.DateTimeField(auto_now_add=True)),
                ('id_conn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Conn_inst_acc')),
            ],
        ),
        migrations.CreateModel(
            name='Inst_accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_inst', models.CharField(db_index=True, max_length=32, unique=True)),
                ('id_inst', models.CharField(default='', max_length=32)),
                ('full_name_inst', models.CharField(default='', max_length=32)),
                ('avatar_link_inst', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_like', models.IntegerField(default=0)),
                ('count_follow', models.IntegerField(default=0)),
                ('count_unfollow', models.IntegerField(default=0)),
                ('id_conn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Conn_inst_acc')),
            ],
        ),
        migrations.AddField(
            model_name='conn_inst_followers',
            name='id_inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Inst_accounts'),
        ),
        migrations.AddField(
            model_name='conn_acc_details',
            name='id_login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Conn_inst_acc'),
        ),
    ]
