# Generated by Django 2.1.7 on 2019-02-22 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.CharField(max_length=12)),
                ('date_act', models.DateTimeField(auto_now_add=True)),
                ('id_conn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Conn_inst_acc')),
                ('inst_acc', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Conn_inst_followers')),
            ],
        ),
    ]
