# Generated by Django 2.1.7 on 2019-02-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_acts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config_instagram_work',
            name='FINISH_COUNT_POSTS',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='config_instagram_work',
            name='FINISH_SLEEP_TIME_FOLLOWER',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='config_instagram_work',
            name='FINISH_SLEEP_TIME_LIKE',
            field=models.IntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='config_instagram_work',
            name='FINISH_SLEEP_TIME_TO_FOLLOW',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='config_instagram_work',
            name='FINISH_SLEEP_TIME_TO_UNFOLLOW',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='config_instagram_work',
            name='MAX_FOLLOWING_USERS_PER_DAY',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='config_instagram_work',
            name='MAX_FOLLOWING_USERS_PER_HOUR',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='config_instagram_work',
            name='MAX_LIKE_PER_DAY',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='config_instagram_work',
            name='MAX_RELATIVE_UNFOLLOWING_USERS_PER_DAY',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='config_instagram_work',
            name='MAX_UNRELATED_UNFOLLOWING_USERS_PER_DAY',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='config_instagram_work',
            name='START_COUNT_POSTS',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='config_instagram_work',
            name='START_SLEEP_TIME_FOLLOWER',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='config_instagram_work',
            name='START_SLEEP_TIME_LIKE',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='config_instagram_work',
            name='START_SLEEP_TIME_TO_FOLLOW',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='config_instagram_work',
            name='START_SLEEP_TIME_TO_UNFOLLOW',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='config_instagram_work',
            name='TIME_LAST_ACTIVITY_LIKE',
            field=models.IntegerField(default=1814400),
        ),
    ]
