# Generated by Django 2.1.7 on 2019-02-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190223_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conn_inst_acc',
            name='first_load',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='conn_inst_acc',
            name='mass_follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conn_inst_acc',
            name='mass_likes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conn_inst_acc',
            name='mass_resort',
            field=models.BooleanField(default=False),
        ),
    ]
