# Generated by Django 2.1.7 on 2019-02-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_acts_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acts',
            name='inst_acc',
        ),
    ]
