# Generated by Django 2.1.7 on 2019-02-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_acts_inst_acc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acts',
            old_name='date_act',
            new_name='date_add',
        ),
    ]
