# Generated by Django 2.1.7 on 2019-02-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190225_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='acts',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acts',
            name='date_stop',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
