# Generated by Django 2.1.7 on 2019-02-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190225_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='date_stat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
