# Generated by Django 2.1.7 on 2019-02-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_notices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acts',
            new_name='Acts_like',
        ),
    ]
