# Generated by Django 2.1.7 on 2019-02-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_acts_follow_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acts_follow',
            name='target',
            field=models.CharField(default='', max_length=32),
        ),
    ]
