# Generated by Django 2.1.7 on 2019-02-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190227_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='acc_in_act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Conn_inst_acc')),
                ('id_inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Inst_accounts')),
            ],
        ),
    ]
