# Generated by Django 2.1.7 on 2019-02-28 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_acc_in_act'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acc_in_act',
            name='id_conn',
        ),
        migrations.AddField(
            model_name='acc_in_act',
            name='target',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Acts_follow'),
            preserve_default=False,
        ),
    ]
