# Generated by Django 2.1.7 on 2019-03-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_acts_follow_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='conn_inst_followers',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='conn_inst_followers',
            name='like_it',
            field=models.BooleanField(default=False),
        ),
    ]
