# Generated by Django 2.1.7 on 2019-03-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190302_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='acts_like',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conn_inst_followers',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
