# Generated by Django 2.1.7 on 2019-03-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190302_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conn_inst_acc',
            old_name='mass_follow',
            new_name='mass_follow_account',
        ),
    ]
