# Generated by Django 2.1.7 on 2019-03-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190305_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conn_inst_acc',
            old_name='mass_follow_account',
            new_name='mass_follow_acc',
        ),
    ]
