# Generated by Django 2.1.7 on 2019-03-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190305_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='conn_inst_acc',
            name='mass_follow_geo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conn_inst_acc',
            name='mass_follow_tag',
            field=models.BooleanField(default=False),
        ),
    ]
