# Generated by Django 2.1.7 on 2019-03-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190307_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acts_follow',
            name='act',
            field=models.CharField(choices=[('follow_acc', 'Целевой аккаунт'), ('follow_geo', 'Целевой город'), ('follow_tag', 'Целевой тег')], max_length=20),
        ),
    ]
